@startuml seq_mensaje_grupal
title Flujo 3 — Mensaje Grupal (Broadcast)

skinparam sequenceArrowThickness 1.5
skinparam sequenceParticipantBorderColor #666666
skinparam sequenceLifeLineBorderColor #AAAAAA
skinparam defaultFontSize 12
skinparam shadowing false

actor       "Emisor E"      as E
participant "Cliente E"     as CLIE
participant "ManejadorCliente E" as MCE
participant "GroupManager"      as GM
participant "SessionManager"    as SM
participant "ManejadorCliente M1" as MCM1
participant "ManejadorCliente M2" as MCM2

E    ->  CLIE : enviar mensaje al grupo "sala1"
CLIE ->  MCE  : PaqueteMensaje(de=E, para="sala1", esGrupo=true)
MCE  ->  GM   : obtenerCopiaMiembros("sala1")
GM   --> MCE  : [E, M1, M2]  — copia defensiva

note right of GM
  readLock().lock()
  Lecturas concurrentes permitidas.
  Devuelve new ArrayList<>(miembros).
end note

loop por cada miembro ≠ E  (ej: M1, M2)
    MCE -> SM : obtenerSesion(miembro)
    alt miembro conectado
        SM  --> MCE  : ManejadorCliente del miembro
        MCE ->  MCM1 : enviarObjeto(PaqueteMensaje)\n[ej: entrega a M1 ó M2]
        MCM1 -->     : entrega a cliente
    else miembro desconectado
        SM  --> MCE  : null
        MCE ->  MCE  : omisión silenciosa\n(System.err — emisor NO notificado)
    end
end

@enduml
